### ISSUE TITLE
wrcp, maptop menu

### ISSUE THREAD

**Issue by UltraSHIM** [Ciallo-Ani/surftimer#14]
Is it possible to fix the !maptop, !wrcp to disable the style menu if there is no record for a specific style
and !wrcp's stage select menu to also disable the menu if there is no record on specific stage?
(like !wr menu)

sorry my bad english

**Comment by Nyano1337** [comment]
Easy to fix, yeah
You seems to have interest in my timer, **But i dont recommend u to use it now**, because i dont have time to keep dis timer work fine until this year september
As far as i know, there's still **some bugs** everyone shouldn't touch, which are fixed in my private git repo but **not fixed** in the github repo.

**Feel free to send more bugs, thank you**
